name: practice-github-actions
on: [pull_request_target]
  types:
    - opened
    branches:    
      - 'main/**'  
jobs:
  practice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'      
      - name: Build the stack
        run: ./runIntegrationTests.sh
      - run: go version
